### ISSUE TITLE
Add a detection for issue drafts.

### ISSUE THREAD

**Issue by dbriemann** [dbriemann/glyph#6]
Currently an issue needs to be closed to not have it published. While it is possible to handle drafts this way it is a bit cumbersome.

Idea: As long as an issue has a label called _draft_ attached it is not exported to HTML.

**Comment by slathrop** [comment]
...and consider the scenario of adding the *draft* label again *after* an issue has already been previously exported to HTML, so that you can un-publish. 😀

**Comment by dbriemann** [comment]
In fact this will be possible automatically as soon as I implement this feature. Glyph just checks if the label is there and if so it will exclude the issue from exporting. So un-publishing will also be possible! :)

**Comment by dbriemann** [comment]
This feature is now implemented as of release **v0.2.6-beta**.
